---
apiVersion: v1
kind: Service
metadata:
  name: unifi-udp
spec:
  loadBalancerIP: 192.168.20.234

---
apiVersion: v1
kind: Service
metadata:
  name: unifi-tcp
spec:
  loadBalancerIP: 192.168.20.234
