---
- name: Apply Proxmox VE specific configs
  hosts: proxmox_servers
  become: true

  handlers:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

  pre_tasks:
    - name: Ensure PVE enterprise apt repo is absent
      ansible.builtin.apt_repository:
        repo: "deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
        state: absent
        update_cache: false
      notify: Update apt cache

    - name: Ensure PVE no-subscription apt repo is present
      ansible.builtin.apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
        state: present
        update_cache: false
      notify: Update apt cache

  roles:
    - notmycloud.pve_discord_dark
