---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./github-arc/
  - ./home-assistant/
  - ./kube-prometheus-stack/
  - ./pi-hole/
  - ./plex/
  - ./tautulli/
  - ./unifi/
  - ./uptime-kuma/
  - ./wizarr/
